mqtt:
  host: 192.168.9.21

ffmpeg:
  global_args: -hide_banner -loglevel error

  # copied from page for reqolink 410/520.
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer+genpts+discardcorrupt
    - -flags
    - low_delay
    - -strict
    - experimental
    - -analyzeduration
    - 1000M
    - -probesize
    - 1000M
#    - -rw_timeout
#    - "5000000"
#    - -use_wallclock_as_timestamps
#    - "1"

  output_args:
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy

cameras:
  catcam:
    ffmpeg:
      inputs:
        # apparently the http endpoint doesn't work with my cameras.
        - path: rtsp://{FRIGATE_CAM_UN}:{FRIGATE_CAM_PW}@192.168.9.53:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://{FRIGATE_CAM_UN}:{FRIGATE_CAM_PW}@192.168.9.53:554/h264Preview_01_main
          roles:
            - clips
    width: 640
    height: 480
    fps: 7


    motion:
      mask:
        - 630,10,630,32,440,32,440,10
    best_image_timeout: 60
    detect:
      enabled: True
    clips:
      enabled: True
      pre_capture: 15
      post_capture: 15
    record:
      enabled: False
    rtmp:
      enabled: False

    snapshots:
      enabled: True
      bounding_box: True

  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAM_UN}:{FRIGATE_CAM_PW}@192.168.9.51:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://{FRIGATE_CAM_UN}:{FRIGATE_CAM_PW}@192.168.9.51:554/h264Preview_01_main
          roles:
            - clips
    width: 640
    height: 480
    fps: 7

    motion:
      mask:
        - 410,444,410,470,221,470,221,444
    objects:
      track:
        - car
        - person
        - cat
        - dog
        - bus
        - bicycle
        - suitcase
        - handbag
        - backpack
        - baseball bat
        - bottle

    best_image_timeout: 60
    detect:
      enabled: True
    clips:
      enabled: True
      pre_capture: 15
      post_capture: 15
    record:
      enabled: False
    rtmp:
      enabled: False
    snapshots:
      enabled: True
      bounding_box: True
  
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAM_UN}:{FRIGATE_CAM_PW}@192.168.9.52:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://{FRIGATE_CAM_UN}:{FRIGATE_CAM_PW}@192.168.9.52:554/h264Preview_01_main 
          roles:
            - clips
    width: 640
    height: 480
    fps: 7


    motion:
      mask:
        - 410,444,410,470,221,470,221,444
    best_image_timeout: 60
    detect:
      enabled: True
    clips:
      enabled: True
      pre_capture: 15
      post_capture: 15
    record:
      enabled: False
    rtmp:
      enabled: False
    snapshots:
      enabled: True
      bounding_box: True

snapshots:
  retain:
    default: 14

clips:
  retain:
    default: 14

detect:
  max_disappeared: 35        

objects:
  track:
    - person
    - cat
    - dog

detectors:
  coral1:
    type: edgetpu
    device: pci

